replicaCount: 3

image:
  repository: piyushmaurya/etests-django
  versionTag: latest

configMapName: etests-config
secretName: etests-secret

containerPort: 8000

service:
  port: 80
  targetPort: 8000
  type: ClusterIP

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

hpa:
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 50

ingress:
  enabled: true
  type: gke
  class: gce
  host: etests.co.in
  gke:
    staticIpName: etests-django
    managedCert: managed-cert

managedCert:
  supported: true
  name: managed-cert
  domains:
    - etests.co.in
    - www.etests.co.in