replicaCount: 3

image:
  repository: piyushmaurya/etests-django
  versionTag: 78be58f90ff9aba1b0b628360a02f04a16abaa2f

configMapName: etests-config
secretName: etests-secret

containerPort: 8000

service:
  port: 80
  targetPort: 8000
  type: ClusterIP

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

hpa:
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 50

ingress:
  enabled: true
  type: minikube
  class: nginx
  host: localhost

managedCert:
  supported: false